_wandb:
    value:
        cli_version: 0.24.0
        e:
            6jjgdibwz8nvsqoxtjye25mca7x4453x:
                args:
                    - --batch_size=64
                    - --dropout=0.2
                    - --kernel_size=3
                    - --learning_rate=0.00011649679991839268
                    - --num_conv_layers=3
                    - --patch_size=128
                    - --regressor_hidden_size=128
                    - --start_channels=16
                    - --target_overlap_percentage=0.25
                    - --transform_name=fft_dct
                    - --weight_decay=1.0954257266957737e-06
                codePath: src/train.py
                codePathLocal: src/train.py
                email: bmorissette8213@gmail.com
                executable: /home/bmorissette/biofilm-cnn-pipeline/.venv/bin/python
                git:
                    commit: 731dcc3db895ae419a4feab04eda31b61ff73dea
                    remote: https://github.com/brianmorissette/biofilm-cnn-pipeline.git
                host: Brians-Yoga
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.35
                program: /home/bmorissette/biofilm-cnn-pipeline/src/train.py
                python: CPython 3.12.11
                root: /home/bmorissette/biofilm-cnn-pipeline
                startedAt: "2026-01-29T00:19:22.091308Z"
                writerId: 6jjgdibwz8nvsqoxtjye25mca7x4453x
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 14
            "4": 3.12.11
            "5": 0.24.0
            "12": 0.24.0
            "13": linux-x86_64
batch_size:
    value: 64
dropout:
    value: 0.2
kernel_size:
    value: 3
learning_rate:
    value: 0.00011649679991839268
num_conv_layers:
    value: 3
patch_size:
    value: 128
regressor_hidden_size:
    value: 128
start_channels:
    value: 16
target_overlap_percentage:
    value: 0.25
transform_name:
    value: fft_dct
weight_decay:
    value: 1.0954257266957737e-06
