wandb_version: 1

batch_size:
  value: 16
dropout:
  value: 0.2
epochs:
  value:
  - 50
  - 100
kernel_size:
  value: 5
learning_rate:
  value: 0.0016026937224300996
num_layers:
  value: 4
patch_size:
  value: 80
regressor_hidden_size:
  value: 256
start_channels:
  value: 16
target_overlap_pct:
  value: 0
transform_name:
  value: none
weight_decay:
  value: 0.00011159533623060268
