wandb_version: 1

batch_size:
  value: 16
dropout:
  value: 0.5
epochs:
  value:
  - 50
  - 100
kernel_size:
  value: 3
learning_rate:
  value: 0.0011066562637177676
num_layers:
  value: 4
patch_size:
  value: 128
regressor_hidden_size:
  value: 256
start_channels:
  value: 32
target_overlap_pct:
  value: 0
transform_name:
  value: fft_dct
weight_decay:
  value: 2.3091602790938147e-06
